apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: first-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /coolpage
        pathType: Prefix
        backend:
          service:
            name: my-internal-service
            port:
              number: 80
# reffer link - https://kubernetes.github.io/ingress-nginx/deploy/ 
