# Here we are creating a pod, jisme ek secret jo ki already created hai, vo inject hoga.
# We are injecting the secret - all  variables at once


apiVersion: v1  # these 2 sections are fixed as per (kubectl explain <resource name>)
kind: Pod
metadata: # data about data
  name: pod-secret-all-variables
spec:
  containers:  # it’s an array, you will specify all the containers
    - name: containername
      image: nginx #hum ek hi container ki image ko  use karre hai 
      imagePullPolicy: Never     # kubernet first check the image in local machine

      envFrom: # we are injecting all the secret at once
       - secretRef:
           name: mysecret # this requires only secret name
