# Here we are creating a pod, jisme ek secret jo ki already created hai, vo inject hoga.
# We are injecting the secret - as a file
# We are going to mount a voume ( voume type - secret) 


apiVersion: v1  # these 2 sections are fixed as per (kubectl explain <resource name>)
kind: Pod
metadata: # data about data
  name: pod-secret-as-file
spec:
  containers:  # it’s an array, you will specify all the containers
    - name: containername
      image: nginx #hum ek hi container ki image ko  use karre hai 
      imagePullPolicy: Never     # kubernet first check the image in local machine
      
      volumeMounts:               # secret ko as a file lene ke liye, humko ek volume mount karna hoga
       -  mountPath: /secrets-dir  # ye wali directory ke andar secret banega
          name: my-secret-volume  # both the volume names should be same

  volumes:    # we have to create a volume
   -  name: my-secret-volume  # both the volume names should be same
      secret:
        secretName: mysecret

