apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-deployment-new
  annotations: 
    kubernetes.io/change-cause: "This is again latest  version" 
spec:
  minReadySeconds: 10 
  replicas: 5 
  selector:
    matchLabels:
      app: myapp1
  strategy:
    type: Recreate
  template:
    metadata:
      name: dippu-pod-new
      labels:
        app: myapp1
    spec:
      containers:
      - name: dippu-container
        image: coolgourav147/nginx-custom
