apiVersion: v1
kind: Pod
metadata:
  name: pod-without-limits2
  labels:
    app: mylabel
spec:
  containers:
  - name: my-app-container
    image: coolgaurav147/nginx-custom
    imagePullPolicy: Never
    resources:
#      requests:
#        cpu: 0.1
#        memory: 250Mi
      limits:
        cpu: 200m
        memory: 200Mi
