apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller2
spec:
  replicas: 3 
  selector:
    app: myapp2
  template:
    metadata: 
      name: mypod
      labels:
        app: myapp2
        app: backend
    spec:
      containers:
      - name: chutiya-container
        image: coolgourav147/nginx-custom

#
#----------------------------------------------------------------------
#
#apiVersion: v1
#kind: ReplicationController
#metadata:
#  name: rcontroller-nginx
#spec:
#  replicas: 3
#  selector:
#    app: my-nginx-app
#  template:
#    metadata:
#      name: nginx-pod
#      labels:
#        app: my-nginx-app
#      spec:
#      containers:
#        - name: nginx-container
#          image: coolgourav147/nginx-custom
