apiVersion: v1
kind: Pod
metadata:
  name: pod-with-cm-as-file
spec:
  containers:
  - image: redis
    name: redis-container
    volumeMounts:
      - name: my-volume
        mountPath: "/etc/my-dir" 
        readOnly: true

  volumes:
    - name: my-volume
      configMap:
        name: cm-from-commandline2  

